---
- name: Installing and Launching Metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install metricbeat .deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/roles/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure system module
    command: metricbeat modules enable docker

  - name: Setup metricbeat
    command: metricbeat setup

  - name: Start metricbeat service
    command: service metricbeat start
